#!url=https://github.com/zhousanfu/rules/edit/master/Shadowrocket/Apps.module
#!name=Apps
#!desc=Apps
#!𝐑𝐞𝐯𝐞𝐧𝐮𝐞𝐂𝐚𝐭多合一脚本[墨鱼版]


[Script]
Apps=type=http-response,pattern=^https?:\/\/api\.revenuecat\.com\/v1\/(receipts|subscribers\/\$RCAnonymousID%3A\w{32})$,requires-body=1,script-path=https://gist.githubusercontent.com/ddgksf2013/dbb1695cd96743eef18f3fac5c6fe227/raw/revenuecat.js

[MITM]
hostname = %APPEND% api.revenuecat.com
